### ISSUE TITLE
_searchOnTitle throws IndexError: list index out of range

### ISSUE THREAD

**Issue by oguelich** [clinton-hall/couchpotato.provider.quorks#1]
Search doesn't work completely on this search provider. It writes an IndexError into log.

05-07 15:10:03 ERROR [.providers.torrent.quorks] Failed to parsing Quorks: Traceback (most recent call last):
  File "C:\Users<username>\AppData\Roaming\CouchPotato\application\CouchPotato-2.4.0.win32\couchpotato\core\providers\torrent\quorks\main.py", line 64, in _searchOnTitle
IndexError: list index out of range

**Comment by clinton-hall** [comment]
Sorry... I missed this. I assumed I would get notifications for any issue on any of my repositories, but apparently I have to specify that I want to Follow this repository!!!

So, I am now following.

The issue here appears to be that the 2nd download link (magnet link) didn't exist. I can put a "safe" escape for this... but can you confirm if this happens for every movie, or just some?

Or indeed is this still an issue?
